### ISSUE TITLE
packageのバージョンアップ後に @storybook/addon-storyshots  が動作しなくなったので改修

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-frontend#113]
# Done の定義

- エラーが解消され、スナップショットテストが利用出来る状態になっている事

# 補足情報

```
 FAIL  src/__tests__/storybook.test.ts (11.495 s)
  ● Console

    console.error
      The above error occurred in the <storyFn> component:

          at storyFn (/Users/kogakeita/gitrepos/lgtm-cat-frontend/node_modules/@storybook/client-api/dist/cjs/story_store.js:723:30)

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)

  ● Storyshots › src/components/Error.tsx › Show Error

    TypeError: Cannot read property 'STORYBOOK_HOOKS_CONTEXT' of undefined

      at node_modules/@storybook/addons/dist/cjs/hooks.js:232:36
      at node_modules/@storybook/client-api/dist/cjs/decorators.js:88:12
      at node_modules/@storybook/addons/dist/cjs/hooks.js:262:20
      at storyFn (node_modules/@storybook/client-api/dist/cjs/story_store.js:723:30)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8744:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9966:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13404:18)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
      at flushSyncCallbackQueueImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2532:9)
      at flushSyncCallbackQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2519:3)
```

**Comment by keitakn** [comment]
実行時のコードはこんな感じ。

```
import initStoryshots, {
  multiSnapshotWithOptions,
} from '@storybook/addon-storyshots';

jest.mock('../hooks/useClipboardMarkdown', () => () => '');

initStoryshots({ test: multiSnapshotWithOptions() });
```

**Comment by keitakn** [comment]
https://github.com/nekochans/lgtm-cat-frontend/pull/112 でJESTのスナップショットテストを作る事で対応する事にしたので、こちらはクローズ。
